services:
  payment-service:
    image: origemglobaltecnologia/origem-payment:latest
    container_name: payment-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SERVER_SERVLET_CONTEXT_PATH=/api
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - RABBIT_URL=${RABBIT_URL}
    restart: always

  notification-service:
    image: origemglobaltecnologia/origem-notification:latest
    container_name: notification-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_RABBITMQ_HOST=${SPRING_RABBITMQ_HOST}
      - SPRING_RABBITMQ_PORT=${SPRING_RABBITMQ_PORT}
      - SPRING_RABBITMQ_USERNAME=${SPRING_RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${SPRING_RABBITMQ_PASSWORD}
      - SPRING_RABBITMQ_VIRTUAL_HOST=${SPRING_RABBITMQ_VIRTUAL_HOST}
    volumes:
      - ./logs:/logs
    restart: always

  origem-pay:
    image: origemglobaltecnologia/origem-pay:latest
    container_name: origem-pay
    ports:
      - "4200:80"
    restart: always
