server:
  port: ${PORT:8080}
logging:
  file:
    name: ../logs/payment-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] [%thread] %-5level %logger{36} - %msg%n"

spring:
  application:
    name: payment-service
  datasource:
    url: ${DB_URL}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    addresses: ${RABBIT_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
